- name: install and run nginx
  hosts: web
  become: yes
  tasks:
  - name: installl nginx
    ansible.builtin.dnf:
      name: nginx
      state: latest
  - name: run nginx
    ansible.builtin.service:
     name: nginx
     state: started
     enable: yes
