- name: variables from prompt
  hosts: localhost
  vars_prompt:
  - name: USERNAME
    prompt: Please enter user name
    private: false
  - name: PASSWORD
    prompt: Please enter password
    private: true
  tasks:
  - name: print iformation
    ansible.builtin.debug:
    msg: "Hi Usernmae {{USERNAME}} and Password is {{PASSWORD}}"
