- name: default value
  hosts: localhost
  tasks:
  - name: print default value
    ansible.builtin.debug:
      msg: "Hellow {{Course | default ('Ansible')}}"

- name: Upper Case
  hosts: localhost
  vars:
    greetings: Hello, Good Morning
  tasks:
  - name: Convert to upper case
    ansible.builtin.debug:
      msg: "Upper cases is: {{greetings | upper}}"

- name: Lower Case
  hosts: localhost
  vars:
    greetings: Hello, Good Morning
  tasks:
  - name: Convert to Lower case
    ansible.builtin.debug:
      msg: "Lower cases is: {{greetings | lower}}"

- name: Remove duplicates
  hosts: localhost
  vars:
    Numbers: [1,2,3,3,3,4,4,5,5]
  tasks:
  - name: Remove duplicates
    ansible.builtin.debug:
      msg: "After removing duplicates Numbers: {{Numbers | unique}}"

- name: Print min and max
  hosts: localhost
  vars:
    age: [14,18,26,36,49]
  tasks:
  - name: Print min and max age
    ansible.builtin.debug:
      msg: "Min age is: {{age | min}}, Max age is: {{age | max}}"

- name: convert dictionary into items/list
  hosts: localhost
  vars:
    my_dict: # this is called as dictionary or map or key/value pairs.
      Course: Ansbile
      Trainer: Sivakumar
      Duration: 120hr
  tasks:
  - name: before convert
    ansible.builtin.debug:
      msg: "Before convert: {{ my_dict }}"
  - name: after convert
    ansible.builtin.debug:
      msg: "After convert: {{ my_dict | dict2items }}"

- name: convert items to dictionary
  hosts: localhost
  vars:
    my_list:
    - {'key': 'Course', 'value': 'Ansbile'}
    - {'key': 'Trainer', 'value': 'Sivakumar'}
    - {'key': 'Duration', 'value': '120hr'}
  tasks:
  - name: before convert
    ansible.builtin.debug:
      msg: "Before convert: {{ my_list }}"
  - name: after convert
    ansible.builtin.debug:
      msg: "After convert: {{ my_list | items2dict }}"