- name: default value
  hosts: localhost
  tasks:
  - name: print default value
    ansible.builtin.debug:
      msg: "Hellow {{Course | default ('Ansible')}}"

- name: Upper Case
  hosts: localhost
  vars:
    greetings: Hello, Good Morning
  tasks:
  - name: Convert to upper case
    ansible.builtin.debug:
      msg: "Upper cases is: {{greetings | upper}}"

- name: Lower Case
  hosts: localhost
  vars:
    greetings: Hello, Good Morning
  tasks:
  - name: Convert to Lower case
    ansible.builtin.debug:
      msg: "Lower cases is: {{greetings | lower}}"

- name: Remove duplicates
  hosts: localhost
  vars:
    Numbers: [1,2,3,3,3,4,4,5,5]
  tasks:
  - name: Remove duplicates
    ansible.builtin.debug:
      msg: "After removing duplicates Numbers: {{Numbers | unique}}"