- name: install packages
  hosts: localhost
  become: yes
  tasks:
  - name: install packages
    ansible.builtin.dnf:
      name: "{{Item}}"
      state: latest
    loop:
    - nginx
    - mysql
    - postfix